name: Publish to npm and Create GitHub Release

on:
  workflow_dispatch: # Manual trigger via GitHub UI or API

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Checks out the repository code to the runner

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Node.js 20 LTS
          registry-url: 'https://registry.npmjs.org' # Default registry for npm
        # Sets up Node.js environment for the workflow

      - name: Install dependencies
        run: npm ci
        # Installs dependencies using npm ci for a clean install

      - name: Build project
        run: npm run build
        # Builds the project using the build script defined in package.json

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Authentication for npm
        # Publishes the package to npm using the token stored in GitHub secrets

      - name: Extract version from package.json
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Extracted version: $VERSION" # Debugging output
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        # Extracts the version from package.json and sets it in the environment

      - name: Delete existing tag if present
        run: |
          git tag -d ${{ env.VERSION }} || true
          git push origin :refs/tags/${{ env.VERSION }} || true
        # Deletes the tag locally and remotely, ignores errors if not present

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
        # Creates a new release on GitHub with the version from package.json

      - name: npm pack
        run: npm pack # Creates a .tgz file from the package.json
        # This will create a file named came.plus-test-<version>.tgz in the current directory 

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use default GITHUB_TOKEN with updated permissions
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # URL from create-release step
          asset_path: ./came.plus-test-${{ env.VERSION }}.tgz # Path to the .tgz file
          asset_name: came.plus-test-${{ env.VERSION }}.tgz # Name of the asset in the release
          asset_content_type: application/gzip # Content type for .tgz files
        # Uploads the .tgz file created by npm pack to the GitHub release

      - name: List all files
        run: |
          echo "Listing all files in the current directory: $(pwd)"
          ls -R
        # Lists all files in the current directory
